name: Platformer Generated test Build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on:
      - ubuntu-latest
    env:
      SERVICE_NAME: nj93/test
    steps:
      - uses: actions/checkout@v2
      - name: Set Version
        id: event-version
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Login to Docker Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image
        run: docker build --tag ${SERVICE_NAME}:${{steps.event-version.outputs.SOURCE_TAG
          }} --file Dockerfile .
      - name: Docker Push
        run: docker push $SERVICE_NAME:$TAG
      - name: Platformer Deploy
        uses: platformer-com/build-deploy-action@v1
        with:
          org-id: ${{secrets.ORG_ID_8e72a7ad-a394-42e3-be56-5c5e3463a0e4}}
          project-id: ${{secrets.PROJECT_ID_8e72a7ad-a394-42e3-be56-5c5e3463a0e4}}
          token: ${{secrets.AUTOGENERATED_CICD_8e72a7ad-a394-42e3-be56-5c5e3463a0e4}}
          image-name: $SERVICE_NAME
          tag: ${{steps.event-version.outputs.SOURCE_TAG }}
          container-id: 1bb7fbd1-e767-47b7-84fd-1f3ec3f240ff
